version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: story-app-server
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      - NODE_ENV=development
      - PORT=8085
      - MONGODB_URI=mongodb://mongodb:27017/story-app
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: story-app-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=story-app

volumes:
  mongodb_data: 